
on:
  push:
    branches:
      - main

  jobs:
    RunUnitTests:
    runs-on: ubuntu-latest

    - name: checkout code
      run: actions/checkout@v4

    - name: install pytest
      run: pip install pytest pytest-spec pytest-describe

    - name: run tests
      run: pytest --spec




   

